### ISSUE TITLE
Positional Encoding for discrete 3D points

### ISSUE THREAD

**Issue by yokinglou** [tatp22/multidim-positional-encoding#1]
Firstly, thanks for your code sharing.

I am curious about that can I directly use the PE3D for discrete 3D points? In your implementation, you use `torch.arange()` to generate `x, y, z`. I wonder whether PE3D still works if I use discrete point coordinates (e.g. (0.1, 0.8, 0.3)) to replace them.

**Comment by tatp22** [comment]
Hi @yokinglou!

Hi, yes, this should still work if you put in these discrete points, at least from the view of the function itself. However, I originally meant this repo to work with large 3,4 and 5 dimensional tensors, so you might have to do a tiny bit of work in order to get a version working if you wanna use discrete points.

Let me know if you have any more questions.

**Comment by yokinglou** [comment]
Hi @tatp22!

Thanks for your reply. I will try it.
